"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Download, ExternalLink, LogOut, Save, ShieldAlert, Sparkles, Trash2 } from "lucide-react";
import { MATCH_STATUS_LABELS, STAGE_LABELS, TOURNAMENT_STATUS_LABELS } from "@/lib/constants";
import { formatDateTime } from "@/lib/format";
import { calculateAllStandings, getExpectedGroupMatchCount } from "@/lib/tournament/groups";
import type { GroupCode, HistoricalRanking, Match, MatchStatus, RankingOverride, Team, TournamentSettings, TournamentStatus } from "@/types/tournament";

type Props = { teams: Team[]; matches: Match[]; ranking: HistoricalRanking[]; settings: TournamentSettings; overrides: RankingOverride[]; connected: boolean };
type Tab = "overview" | "teams" | "matches" | "ties" | "finals" | "ranking" | "settings" | "export";

const tabs: Array<[Tab, string]> = [["overview","Dashboard"],["teams","Coppie e gironi"],["matches","Risultati"],["ties","Parità"],["finals","Fase finale"],["ranking","Ranking"],["settings","Comunicazione"],["export","Esporta"]];

async function parseResponse(response: Response) {
  const result = await response.json() as { error?: string; message?: string; confirmationRequired?: boolean; affected?: string[]; count?: number };
  if (!response.ok) throw Object.assign(new Error(result.error || "Operazione non riuscita."), { result });
  return result;
}

export function AdminDashboard(props: Props) {
  const router = useRouter();
  const [tab, setTab] = useState<Tab>("overview");
  const [message, setMessage] = useState("");
  const [error, setError] = useState(false);
  const [busy, setBusy] = useState(false);
  const standings = useMemo(() => calculateAllStandings(props.teams, props.matches, props.overrides), [props.teams, props.matches, props.overrides]);
  const complete = props.matches.filter((match) => match.status === "completed").length;
  const groupMatches = props.matches.filter((match) => match.stage === "group");
  const expectedGroupMatches = getExpectedGroupMatchCount(props.teams);
  const expectedMatches = expectedGroupMatches + 8;
  const unresolved = standings.filter((group) => group.unresolvedTie.length > 0);
  const finalsReady = groupMatches.length === expectedGroupMatches && groupMatches.every((match) => match.status === "completed") && unresolved.length === 0 && standings.every((group) => group.isComplete && !group.isProvisional);

  function notify(text: string, isError = false) { setMessage(text); setError(isError); }
  function refreshed(text: string) { notify(text); router.refresh(); }

  async function logout() {
    await fetch("/api/admin/logout", { method: "POST" });
    router.refresh();
  }

  async function generateGroups() {
    if (!props.connected) return notify("Collega prima il database Supabase.", true);
    const warning = props.matches.length > 0
      ? `${props.matches.length} partite esistenti saranno sostituite e i relativi risultati cancellati. Confermi?`
      : `Generare i ${expectedGroupMatches} incontri dei gironi secondo lo schema ufficiale?`;
    if (!window.confirm(warning)) return;
    setBusy(true);
    try {
      const response = await fetch("/api/admin/generate-groups", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ confirmed: props.matches.length > 0 }) });
      const result = await parseResponse(response);
      refreshed(`${result.count ?? expectedGroupMatches} incontri generati.`);
    } catch (cause) { notify(cause instanceof Error ? cause.message : "Generazione non riuscita.", true); }
    finally { setBusy(false); }
  }

  async function generateFinals() {
    const qualified = standings.flatMap((group) => group.rows.slice(0,2).map((row) => `${group.groupCode}${row.rank}: ${row.team.name}`));
    if (!window.confirm(`Qualificate:\n${qualified.join("\n")}\n\nQuarti: A1–B2, C1–D2, B1–A2, D1–C2. Confermi?`)) return;
    setBusy(true);
    try {
      const result = await parseResponse(await fetch("/api/admin/generate-finals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ confirmed: true }) }));
      refreshed(`${result.count ?? 8} incontri della fase finale generati.`);
    } catch (cause) { notify(cause instanceof Error ? cause.message : "Generazione non riuscita.", true); }
    finally { setBusy(false); }
  }

  return (
    <section className="admin-shell">
      <header className="admin-hero"><div><p className="eyebrow">Controllo torneo</p><h1>Dashboard amministratore</h1><p>{TOURNAMENT_STATUS_LABELS[props.settings.tournament_status]} · ultimo aggiornamento {formatDateTime(props.settings.last_public_update)}</p></div><div className="button-row"><a className="button button--primary" href="/" target="_blank" rel="noreferrer"><ExternalLink size={17} aria-hidden="true" /> Sito pubblico</a><button className="button button--outline" onClick={logout} type="button"><LogOut size={17} aria-hidden="true" /> Esci dall’area amministratore</button></div></header>
      {!props.connected && <div className="connection-notice" role="alert"><ShieldAlert size={18} aria-hidden="true" /> Configura le variabili Supabase per abilitare salvataggi e aggiornamenti live. L’interfaccia mostra i dati iniziali ufficiali in sola lettura.</div>}
      <div className="admin-tabs" role="tablist" aria-label="Sezioni amministrazione">{tabs.map(([value,label]) => <button type="button" role="tab" aria-selected={tab === value} className={tab === value ? "is-active" : ""} onClick={() => setTab(value)} key={value}>{label}</button>)}</div>
      <p className={`form-message ${error ? "is-error" : ""}`} aria-live="polite">{message}</p>

      {tab === "overview" && <div className="admin-section"><h2>Situazione del torneo</h2><div className="grid grid--4"><div className="metric"><strong>{expectedMatches}</strong><span>Partite previste</span></div><div className="metric"><strong>{props.matches.length}</strong><span>Partite generate</span></div><div className="metric"><strong>{complete}</strong><span>Partite concluse</span></div><div className="metric"><strong>{Math.max(0, expectedMatches - complete)}</strong><span>Partite mancanti</span></div><div className="metric"><strong>{props.matches.filter((m) => m.status === "live").length}</strong><span>In corso</span></div><div className="metric"><strong>{props.matches.filter((m) => m.status === "postponed").length}</strong><span>Rinviate</span></div><div className="metric"><strong>{unresolved.length}</strong><span>Parità da risolvere</span></div><div className="metric"><strong>{props.settings.finals_generated ? "Sì" : "No"}</strong><span>Fase finale generata</span></div></div><div className="button-row"><button className="button button--navy" onClick={() => setTab("teams")}>Gestisci coppie</button><button className="button button--navy" onClick={() => setTab("matches")}>Inserisci risultati</button><button className="button button--navy" onClick={() => setTab("ties")}>Gestisci parità</button><button className="button button--navy" onClick={() => setTab("finals")}>Genera fase finale</button></div></div>}
      {tab === "teams" && <div className="admin-section"><h2>Gestisci coppie e gironi</h2><p>Modifica nomi, giocatori, assegnazione e ordine oppure rimuovi una coppia. Ogni girone deve conservare almeno tre coppie.</p><div className="admin-list">{props.teams.map((team) => <TeamEditor team={team} key={team.id} disabled={!props.connected} canDelete={props.teams.filter((candidate) => candidate.group_code === team.group_code).length > 3} onSaved={refreshed} onError={(text) => notify(text,true)} />)}</div><button className="button button--blue" type="button" disabled={busy || !props.connected} onClick={generateGroups}><Sparkles size={18} aria-hidden="true" /> Genera incontri dei gironi</button></div>}
      {tab === "matches" && <div className="admin-section"><h2>Inserimento rapido risultati</h2><p>La validazione definitiva avviene sul server: gironi ai 10 punti, fase finale ai 12.</p>{props.matches.length ? <div className="admin-list">{props.matches.map((match) => <MatchEditor key={match.id} match={match} teams={props.teams} disabled={!props.connected} onSaved={refreshed} onError={(text) => notify(text,true)} />)}</div> : <div className="empty-state">Genera prima gli incontri dei gironi.</div>}</div>}
      {tab === "ties" && <div className="admin-section"><h2>Gestisci parità</h2>{props.overrides.length > 0 && <div className="panel panel--gold"><h3>Override di classifica attivi</h3>{props.overrides.slice().sort((a,b)=>a.group_code.localeCompare(b.group_code)||a.manual_rank-b.manual_rank).map((item)=><p key={`${item.group_code}-${item.team_id}`}><strong>Girone {item.group_code} · ordine {item.manual_rank}:</strong> {props.teams.find(team=>team.id===item.team_id)?.name || "Coppia"}{item.reason ? ` — ${item.reason}` : ""}</p>)}</div>}{unresolved.length ? unresolved.map((group) => <TieEditor key={group.groupCode} groupCode={group.groupCode} teams={group.unresolvedTie} rows={group.rows} matches={props.matches} disabled={!props.connected} onSaved={refreshed} onError={(text) => notify(text,true)} />) : <div className="empty-state">Non ci sono parità multiple da risolvere.</div>}</div>}
      {tab === "finals" && <div className="admin-section"><h2>Genera fase finale</h2><p>Disponibile solo dopo che tutti gli incontri dei gironi sono conclusi, con classifiche definitive e nessuna parità irrisolta.</p><div className="grid grid--4">{standings.flatMap((group) => group.rows.slice(0,2).map((row) => <div className="panel" key={row.team.id}><strong>{group.groupCode}{row.rank}</strong><h3>{row.team.name}</h3></div>))}</div><div className="panel panel--cream"><h3>Incroci confermati</h3><ol><li>A1 contro B2</li><li>C1 contro D2</li><li>B1 contro A2</li><li>D1 contro C2</li></ol><p>Semifinali: QF1–QF2 e QF3–QF4. I perdenti delle semifinali vanno alla finale 3°/4°; i vincitori alla finale 1°/2°.</p></div><button className="button button--blue" type="button" disabled={!finalsReady || props.settings.finals_generated || busy || !props.connected} onClick={generateFinals}><Sparkles size={18} aria-hidden="true" /> {props.settings.finals_generated ? "Fase finale già generata" : "Genera fase finale"}</button></div>}
      {tab === "ranking" && <RankingManager ranking={props.ranking} disabled={!props.connected} onSaved={refreshed} onError={(text) => notify(text,true)} />}
      {tab === "settings" && <SettingsEditor settings={props.settings} disabled={!props.connected} onSaved={refreshed} onError={(text) => notify(text,true)} />}
      {tab === "export" && <div className="admin-section"><h2>Esporta dati</h2><p>I file includono coppie, gironi, partite, classifiche, fase finale e ranking storico. Non contengono credenziali, sessioni o tentativi di login.</p><div className="button-row"><a className={`button button--navy ${!props.connected ? "is-disabled" : ""}`} href={props.connected ? "/api/admin/export?format=csv" : undefined}><Download size={18} aria-hidden="true" /> Scarica CSV</a><a className={`button button--blue ${!props.connected ? "is-disabled" : ""}`} href={props.connected ? "/api/admin/export?format=json" : undefined}><Download size={18} aria-hidden="true" /> Scarica JSON</a></div></div>}
    </section>
  );
}

function TeamEditor({ team, disabled, canDelete, onSaved, onError }: { team: Team; disabled: boolean; canDelete: boolean; onSaved: (text:string)=>void; onError:(text:string)=>void }) {
  const [value,setValue] = useState(team); const [busy,setBusy] = useState(false);
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); try { await parseResponse(await fetch("/api/admin/teams", { method:"PUT", headers:{"content-type":"application/json"}, body:JSON.stringify(value) })); onSaved("Coppia salvata."); } catch(cause){onError(cause instanceof Error ? cause.message : "Salvataggio non riuscito.");} finally{setBusy(false);} }
  async function remove() { if (!window.confirm(`Rimuovere ${value.name} dal Girone ${value.group_code}? Saranno eliminati anche gli eventuali incontri del girone che coinvolgono questa coppia.`)) return; setBusy(true); try { const result = await parseResponse(await fetch("/api/admin/teams", { method:"DELETE", headers:{"content-type":"application/json"}, body:JSON.stringify({id:team.id,confirmed:true}) })); onSaved(`${value.name} rimossa. ${result.count ?? 0} incontri collegati eliminati.`); } catch(cause){onError(cause instanceof Error ? cause.message : "Rimozione non riuscita.");} finally{setBusy(false);} }
  return <form className="admin-team-card" onSubmit={save}><h3>{value.name}</h3><div className="form-grid"><div className="field"><label htmlFor={`name-${team.id}`}>Nome coppia</label><textarea id={`name-${team.id}`} value={value.name} onChange={(e)=>setValue({...value,name:e.target.value})} required /></div><div className="field"><label htmlFor={`p1-${team.id}`}>Giocatore 1</label><textarea id={`p1-${team.id}`} value={value.player_one || ""} onChange={(e)=>setValue({...value,player_one:e.target.value})} /></div><div className="field"><label htmlFor={`p2-${team.id}`}>Giocatore 2</label><textarea id={`p2-${team.id}`} value={value.player_two || ""} onChange={(e)=>setValue({...value,player_two:e.target.value})} /></div><div className="field"><label htmlFor={`group-${team.id}`}>Girone</label><select id={`group-${team.id}`} value={value.group_code} onChange={(e)=>setValue({...value,group_code:e.target.value as GroupCode})}>{["A","B","C","D"].map(g=><option key={g}>{g}</option>)}</select></div><div className="field"><label htmlFor={`order-${team.id}`}>Ordine</label><input id={`order-${team.id}`} type="number" min="1" value={value.display_order} onChange={(e)=>setValue({...value,display_order:Number(e.target.value)})} /></div></div><p><strong>Anteprima:</strong> {value.name} — {[value.player_one,value.player_two].filter(Boolean).join(" · ") || "giocatori da definire"}</p><div className="button-row"><button className="button button--navy" type="submit" disabled={disabled || busy}><Save size={17} aria-hidden="true" /> Salva coppia</button><button className="button button--danger" type="button" disabled={disabled || busy || !canDelete} title={canDelete ? "Rimuovi questa coppia" : "Il girone deve conservare almeno tre coppie"} onClick={remove}><Trash2 size={17} aria-hidden="true" /> Rimuovi dal girone</button></div></form>;
}

function MatchEditor({ match, teams, disabled, onSaved, onError }: { match: Match; teams: Team[]; disabled:boolean; onSaved:(text:string)=>void; onError:(text:string)=>void }) {
  const teamName=(id:string|null)=>teams.find(t=>t.id===id)?.name || "Da definire";
  const [one,setOne]=useState<number|null>(match.score_one); const [two,setTwo]=useState<number|null>(match.score_two); const [status,setStatus]=useState<MatchStatus>(match.status); const [court,setCourt]=useState(match.court||""); const [note,setNote]=useState(match.note||""); const [scheduled,setScheduled]=useState(match.scheduled_at ? new Date(match.scheduled_at).toISOString().slice(0,16) : ""); const [busy,setBusy]=useState(false);
  async function save(nextStatus=status, confirmCascade=false){setBusy(true); try{const response=await fetch("/api/admin/matches",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({id:match.id,score_one:one,score_two:two,status:nextStatus,court,note,scheduled_at:scheduled?new Date(scheduled).toISOString():null,confirmCascade})}); if(response.status===409){const warning=await response.json() as {error:string}; if(window.confirm(`${warning.error}\n\nConfermi l’azzeramento delle partite successive?`)){setBusy(false); return save(nextStatus,true);} throw new Error("Correzione annullata.");} const result=await parseResponse(response); onSaved(result.message||"Risultato salvato.");}catch(cause){onError(cause instanceof Error?cause.message:"Salvataggio non riuscito.");}finally{setBusy(false);}}
  return <article className="admin-match-card"><h3>{STAGE_LABELS[match.stage]} {match.group_code?`· Girone ${match.group_code} · Giornata ${match.match_day}`:match.bracket_slot?`· ${match.bracket_slot}`:""}</h3><div className="admin-match-score"><strong>{teamName(match.team_one_id)}</strong><input aria-label={`Punteggio ${teamName(match.team_one_id)}`} type="number" min="0" max={match.stage==="group"?10:12} value={one??""} onChange={(e)=>setOne(e.target.value===""?null:Number(e.target.value))} /></div><div className="admin-match-score"><strong>{teamName(match.team_two_id)}</strong><input aria-label={`Punteggio ${teamName(match.team_two_id)}`} type="number" min="0" max={match.stage==="group"?10:12} value={two??""} onChange={(e)=>setTwo(e.target.value===""?null:Number(e.target.value))} /></div><div className="form-grid"><div className="field"><label htmlFor={`status-${match.id}`}>Stato</label><select id={`status-${match.id}`} value={status} onChange={(e)=>setStatus(e.target.value as MatchStatus)}>{Object.entries(MATCH_STATUS_LABELS).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div><div className="field"><label htmlFor={`when-${match.id}`}>Data e ora</label><input id={`when-${match.id}`} type="datetime-local" value={scheduled} onChange={(e)=>setScheduled(e.target.value)} /></div><div className="field"><label htmlFor={`court-${match.id}`}>Campo</label><input id={`court-${match.id}`} value={court} onChange={(e)=>setCourt(e.target.value)} /></div><div className="field"><label htmlFor={`note-${match.id}`}>Nota</label><textarea id={`note-${match.id}`} value={note} onChange={(e)=>setNote(e.target.value)} /></div></div><div className="button-row"><button className="button button--navy" disabled={disabled||busy} onClick={()=>save(status)} type="button"><Save size={16} aria-hidden="true" /> Salva</button>{(["live","completed","postponed","cancelled"] as MatchStatus[]).map(value=><button className="button button--outline" key={value} disabled={disabled||busy} onClick={()=>{setStatus(value);void save(value);}} type="button">{MATCH_STATUS_LABELS[value]}</button>)}</div></article>;
}

function TieEditor({ groupCode, teams, rows, matches, disabled, onSaved, onError }: { groupCode: GroupCode; teams: Team[]; rows: ReturnType<typeof calculateAllStandings>[number]["rows"]; matches:Match[]; disabled:boolean; onSaved:(text:string)=>void; onError:(text:string)=>void }) {
  const [order,setOrder]=useState<Record<string,number>>(Object.fromEntries(teams.map((team,index)=>[team.id,index+1]))); const [reason,setReason]=useState(""); const [busy,setBusy]=useState(false);
  async function save(){if(!window.confirm(`Confermi l’ordine manuale per il Girone ${groupCode}?`))return;setBusy(true);try{await parseResponse(await fetch("/api/admin/overrides",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({group_code:groupCode,reason:reason||null,confirmed:true,entries:teams.map(team=>({team_id:team.id,manual_rank:order[team.id]}))})}));onSaved(`Parità del Girone ${groupCode} risolta.`);}catch(cause){onError(cause instanceof Error?cause.message:"Salvataggio non riuscito.");}finally{setBusy(false);}}
  const involvedIds=new Set(teams.map(team=>team.id)); const directMatches=matches.filter(match=>match.group_code===groupCode&&match.team_one_id&&match.team_two_id&&involvedIds.has(match.team_one_id)&&involvedIds.has(match.team_two_id)); const teamName=(id:string|null)=>teams.find(team=>team.id===id)?.name||"Coppia";
  return <div className="panel panel--cream"><h3>Girone {groupCode} · Parità da risolvere</h3><p><strong>Motivo dell’ambiguità:</strong> tre o più coppie hanno lo stesso numero di vittorie e la stessa differenza punti; il regolamento non prevede criteri automatici ulteriori.</p>{directMatches.length>0&&<div><h4>Scontri diretti coinvolti</h4><ul>{directMatches.map(match=><li key={match.id}>{teamName(match.team_one_id)} {match.score_one??"–"}–{match.score_two??"–"} {teamName(match.team_two_id)} · {MATCH_STATUS_LABELS[match.status]}</li>)}</ul></div>}{teams.map(team=>{const row=rows.find(item=>item.team.id===team.id);return <div className="admin-ranking-row" key={team.id}><strong>{team.name}</strong><p>Vittorie: {row?.wins??0} · Differenza: {row?.difference??0}</p><div className="field"><label htmlFor={`manual-${team.id}`}>Posizione manuale</label><input id={`manual-${team.id}`} type="number" min="1" max={teams.length} value={order[team.id]} onChange={(e)=>setOrder({...order,[team.id]:Number(e.target.value)})} /></div></div>;})}<div className="field"><label htmlFor={`reason-${groupCode}`}>Motivazione facoltativa</label><textarea id={`reason-${groupCode}`} value={reason} onChange={(e)=>setReason(e.target.value)} /></div><button className="button button--navy" type="button" disabled={disabled||busy} onClick={save}>Salva ordine definitivo</button></div>;
}

function RankingManager({ ranking, disabled, onSaved, onError }: { ranking: HistoricalRanking[]; disabled:boolean; onSaved:(text:string)=>void; onError:(text:string)=>void }) {
  const [newEntry,setNewEntry]=useState({ranking_period:"2020-2025",rank_position:1,participant_name:"",points:0,display_order:ranking.length+1});
  async function action(body:unknown, success:string){try{await parseResponse(await fetch("/api/admin/ranking",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}));onSaved(success);}catch(cause){onError(cause instanceof Error?cause.message:"Operazione non riuscita.");}}
  async function reset(){if(window.confirm("Ripristinare esattamente i 30 record ufficiali iniziali? Tutte le modifiche al ranking saranno eliminate."))await action({action:"reset",confirmed:true},"Ranking ufficiale ripristinato.");}
  return <div className="admin-section"><h2>Gestisci ranking storico</h2><div className="admin-list">{ranking.map(entry=><RankingRow key={entry.id} entry={entry} disabled={disabled} onUpdate={(value)=>action({action:"update",entry:value},"Partecipante aggiornato.")} onDelete={()=>{if(window.confirm(`Eliminare ${entry.participant_name}?`))void action({action:"delete",id:entry.id,confirmed:true},"Partecipante eliminato.");}} />)}</div><div className="panel panel--cream"><h3>Aggiungi partecipante</h3><div className="form-grid"><div className="field"><label htmlFor="new-rank-name">Partecipante</label><textarea id="new-rank-name" value={newEntry.participant_name} onChange={(e)=>setNewEntry({...newEntry,participant_name:e.target.value})} /></div><div className="field"><label htmlFor="new-rank-position">Posizione ufficiale</label><input id="new-rank-position" type="number" min="1" value={newEntry.rank_position} onChange={(e)=>setNewEntry({...newEntry,rank_position:Number(e.target.value)})} /></div><div className="field"><label htmlFor="new-rank-points">Punti</label><input id="new-rank-points" type="number" min="0" value={newEntry.points} onChange={(e)=>setNewEntry({...newEntry,points:Number(e.target.value)})} /></div><div className="field"><label htmlFor="new-rank-order">Ordine</label><input id="new-rank-order" type="number" min="1" value={newEntry.display_order} onChange={(e)=>setNewEntry({...newEntry,display_order:Number(e.target.value)})} /></div></div><button className="button button--navy" disabled={disabled} type="button" onClick={()=>action({action:"add",entry:newEntry},"Partecipante aggiunto.")}>Aggiungi</button></div><button className="button button--danger" type="button" disabled={disabled} onClick={reset}><Trash2 size={17} aria-hidden="true" /> Ripristina i 30 dati iniziali</button></div>;
}

function RankingRow({ entry, disabled, onUpdate, onDelete }: { entry:HistoricalRanking; disabled:boolean; onUpdate:(value:HistoricalRanking)=>void; onDelete:()=>void }) {
  const [value,setValue]=useState(entry);
  return <div className="admin-ranking-row"><div className="form-grid"><div className="field"><label htmlFor={`rank-name-${entry.id}`}>Partecipante</label><textarea id={`rank-name-${entry.id}`} value={value.participant_name} onChange={(e)=>setValue({...value,participant_name:e.target.value})} /></div><div className="field"><label htmlFor={`rank-position-${entry.id}`}>Posizione ufficiale</label><input id={`rank-position-${entry.id}`} type="number" min="1" value={value.rank_position} onChange={(e)=>setValue({...value,rank_position:Number(e.target.value)})} /></div><div className="field"><label htmlFor={`rank-points-${entry.id}`}>Punti</label><input id={`rank-points-${entry.id}`} type="number" min="0" value={value.points} onChange={(e)=>setValue({...value,points:Number(e.target.value)})} /></div><div className="field"><label htmlFor={`rank-order-${entry.id}`}>Ordine</label><input id={`rank-order-${entry.id}`} type="number" min="1" value={value.display_order} onChange={(e)=>setValue({...value,display_order:Number(e.target.value)})} /></div></div><div className="button-row"><button className="button button--navy" disabled={disabled} type="button" onClick={()=>onUpdate(value)}><Save size={16} aria-hidden="true" /> Salva</button><button className="button button--danger" disabled={disabled} type="button" onClick={onDelete}><Trash2 size={16} aria-hidden="true" /> Elimina</button></div></div>;
}

function SettingsEditor({ settings, disabled, onSaved, onError }: { settings:TournamentSettings; disabled:boolean; onSaved:(text:string)=>void; onError:(text:string)=>void }) {
  const [status,setStatus]=useState<TournamentStatus>(settings.tournament_status); const [announcement,setAnnouncement]=useState(settings.public_announcement||""); const [busy,setBusy]=useState(false);
  async function save(event:FormEvent){event.preventDefault();setBusy(true);try{await parseResponse(await fetch("/api/admin/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({tournament_status:status,public_announcement:announcement})}));onSaved("Stato e comunicazione aggiornati.");}catch(cause){onError(cause instanceof Error?cause.message:"Salvataggio non riuscito.");}finally{setBusy(false);}}
  return <form className="admin-section" onSubmit={save}><h2>Stato e comunicazione pubblica</h2><div className="field"><label htmlFor="tournament-status">Stato del torneo</label><select id="tournament-status" value={status} onChange={(e)=>setStatus(e.target.value as TournamentStatus)}>{Object.entries(TOURNAMENT_STATUS_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><div className="field"><label htmlFor="public-announcement">Comunicazione dell’organizzazione</label><textarea id="public-announcement" value={announcement} onChange={(e)=>setAnnouncement(e.target.value)} /></div><button className="button button--navy" disabled={disabled||busy} type="submit"><Save size={17} aria-hidden="true" /> Pubblica aggiornamento</button></form>;
}
